#pragma once
#if !defined(_LSS_1D_SPACE_VARIABLE_GENERAL_HEAT_EQUATION_SOLVERS)
#define _LSS_1D_SPACE_VARIABLE_GENERAL_HEAT_EQUATION_SOLVERS

#include "lss_space_variable_general_heat_equation_dirichlet_solvers.h"
#include "lss_space_variable_general_heat_equation_robin_solvers.h"

#endif  //_LSS_1D_SPACE_VARIABLE_GENERAL_HEAT_EQUATION_SOLVERS
